[package]
name = "mork-interrupt"
version = "0.1.0"
edition = "2024"

[dependencies]
mork-hal = { path = "../mork-hal" }
mork-task = { path = "../mork-task" }
mork-kernel-state = { path = "../mork-kernel-state" }
mork-common = { path = "../../mork-common" }
log = "0.4"